/**
 * ISO 27001:2022 Requirements
 *
 * ISO/IEC 27001:2022 Information Security Management System
 * Annex A Controls (93 controls in 4 themes)
 *
 * A.5 Organizational controls (37)
 * A.6 People controls (8)
 * A.7 Physical controls (14)
 * A.8 Technological controls (34)
 */

import { FrameworkRequirement } from './framework-types';

export const ISO27001_REQUIREMENTS: FrameworkRequirement[] = [
  // ============================================================================
  // A.5 ORGANIZATIONAL CONTROLS (37 controls)
  // ============================================================================
  {
    id: 'iso-A5.1',
    framework: 'iso27001',
    article_number: 'A.5.1',
    title: 'Policies for Information Security',
    description: 'Information security policy and topic-specific policies shall be defined, approved by management, published, communicated, and acknowledged.',
    category: 'A5',
    priority: 'critical',
    evidence_types: ['policy', 'procedure'],
    sort_order: 1,
    implementation_guidance: 'Create comprehensive ISMS policy. Include topic-specific policies (access, crypto, physical). Review annually.',
  },
  {
    id: 'iso-A5.2',
    framework: 'iso27001',
    article_number: 'A.5.2',
    title: 'Information Security Roles and Responsibilities',
    description: 'Information security roles and responsibilities shall be defined and allocated according to organization needs.',
    category: 'A5',
    priority: 'critical',
    evidence_types: ['policy', 'procedure', 'observation'],
    sort_order: 2,
    implementation_guidance: 'Define CISO role, security team responsibilities, and user responsibilities. Document in job descriptions.',
  },
  {
    id: 'iso-A5.3',
    framework: 'iso27001',
    article_number: 'A.5.3',
    title: 'Segregation of Duties',
    description: 'Conflicting duties and conflicting areas of responsibility shall be segregated.',
    category: 'A5',
    priority: 'high',
    evidence_types: ['procedure', 'technical_control', 'access_review'],
    sort_order: 3,
    implementation_guidance: 'Identify conflicting duties. Implement separation between development and production. Use maker-checker.',
  },
  {
    id: 'iso-A5.4',
    framework: 'iso27001',
    article_number: 'A.5.4',
    title: 'Management Responsibilities',
    description: 'Management shall require all personnel to apply information security in accordance with the established policies.',
    category: 'A5',
    priority: 'high',
    evidence_types: ['policy', 'training_records', 'interview'],
    sort_order: 4,
    implementation_guidance: 'Management must actively endorse security. Include security in performance reviews.',
  },
  {
    id: 'iso-A5.5',
    framework: 'iso27001',
    article_number: 'A.5.5',
    title: 'Contact with Authorities',
    description: 'Organization shall establish and maintain contact with relevant authorities.',
    category: 'A5',
    priority: 'medium',
    evidence_types: ['procedure', 'policy'],
    sort_order: 5,
    implementation_guidance: 'Identify regulatory authorities. Document contact procedures. Establish relationships before incidents.',
  },
  {
    id: 'iso-A5.6',
    framework: 'iso27001',
    article_number: 'A.5.6',
    title: 'Contact with Special Interest Groups',
    description: 'Organization shall establish and maintain contact with special interest groups or security forums.',
    category: 'A5',
    priority: 'low',
    evidence_types: ['procedure', 'observation'],
    sort_order: 6,
    implementation_guidance: 'Join ISACs, industry groups. Subscribe to threat intelligence feeds. Participate in security communities.',
  },
  {
    id: 'iso-A5.7',
    framework: 'iso27001',
    article_number: 'A.5.7',
    title: 'Threat Intelligence',
    description: 'Information about threats shall be collected and analyzed to produce threat intelligence.',
    category: 'A5',
    priority: 'high',
    evidence_types: ['technical_control', 'procedure', 'monitoring_evidence'],
    sort_order: 7,
    implementation_guidance: 'Subscribe to threat feeds. Analyze threats relevant to organization. Share intelligence where appropriate.',
  },
  {
    id: 'iso-A5.8',
    framework: 'iso27001',
    article_number: 'A.5.8',
    title: 'Information Security in Project Management',
    description: 'Information security shall be integrated into project management.',
    category: 'A5',
    priority: 'high',
    evidence_types: ['procedure', 'policy', 'audit_report'],
    sort_order: 8,
    implementation_guidance: 'Include security reviews in project gates. Assess security risks for all projects.',
  },
  {
    id: 'iso-A5.9',
    framework: 'iso27001',
    article_number: 'A.5.9',
    title: 'Inventory of Information and Other Associated Assets',
    description: 'An inventory of information and associated assets shall be developed and maintained.',
    category: 'A5',
    priority: 'high',
    evidence_types: ['technical_control', 'procedure'],
    sort_order: 9,
    implementation_guidance: 'Create comprehensive asset inventory. Include data classification. Keep inventory current.',
  },
  {
    id: 'iso-A5.10',
    framework: 'iso27001',
    article_number: 'A.5.10',
    title: 'Acceptable Use of Information and Other Associated Assets',
    description: 'Rules for acceptable use of information and assets shall be identified, documented, and implemented.',
    category: 'A5',
    priority: 'high',
    evidence_types: ['policy', 'procedure', 'training_records'],
    sort_order: 10,
    implementation_guidance: 'Document acceptable use policy. Cover email, internet, mobile devices. Get user acknowledgment.',
  },
  {
    id: 'iso-A5.11',
    framework: 'iso27001',
    article_number: 'A.5.11',
    title: 'Return of Assets',
    description: 'Personnel and other interested parties shall return all organizational assets upon termination.',
    category: 'A5',
    priority: 'medium',
    evidence_types: ['procedure', 'observation'],
    sort_order: 11,
    implementation_guidance: 'Include asset return in offboarding checklist. Track returned assets. Verify before final day.',
  },
  {
    id: 'iso-A5.12',
    framework: 'iso27001',
    article_number: 'A.5.12',
    title: 'Classification of Information',
    description: 'Information shall be classified according to information security needs based on confidentiality, integrity, and availability.',
    category: 'A5',
    priority: 'high',
    evidence_types: ['policy', 'procedure', 'observation'],
    sort_order: 12,
    implementation_guidance: 'Define classification scheme (Public, Internal, Confidential, Restricted). Apply to all information.',
  },
  {
    id: 'iso-A5.13',
    framework: 'iso27001',
    article_number: 'A.5.13',
    title: 'Labelling of Information',
    description: 'An appropriate set of procedures for labelling shall be developed in accordance with classification scheme.',
    category: 'A5',
    priority: 'medium',
    evidence_types: ['procedure', 'technical_control', 'observation'],
    sort_order: 13,
    implementation_guidance: 'Implement labelling standards. Use document headers/footers. Consider automated classification.',
  },
  {
    id: 'iso-A5.14',
    framework: 'iso27001',
    article_number: 'A.5.14',
    title: 'Information Transfer',
    description: 'Rules, procedures, and agreements for transfer of information shall be in place.',
    category: 'A5',
    priority: 'high',
    evidence_types: ['policy', 'procedure', 'technical_control'],
    sort_order: 14,
    implementation_guidance: 'Define secure transfer methods. Implement encryption requirements. Control removable media.',
  },
  {
    id: 'iso-A5.15',
    framework: 'iso27001',
    article_number: 'A.5.15',
    title: 'Access Control',
    description: 'Rules to control physical and logical access to information and assets shall be established.',
    category: 'A5',
    priority: 'critical',
    evidence_types: ['policy', 'procedure', 'technical_control', 'access_review'],
    sort_order: 15,
    implementation_guidance: 'Document access control policy. Implement RBAC. Follow least privilege principle.',
  },
  {
    id: 'iso-A5.16',
    framework: 'iso27001',
    article_number: 'A.5.16',
    title: 'Identity Management',
    description: 'Full lifecycle of identities shall be managed.',
    category: 'A5',
    priority: 'critical',
    evidence_types: ['technical_control', 'procedure'],
    sort_order: 16,
    implementation_guidance: 'Implement identity governance. Manage provisioning/deprovisioning. Use unique identifiers.',
  },
  {
    id: 'iso-A5.17',
    framework: 'iso27001',
    article_number: 'A.5.17',
    title: 'Authentication Information',
    description: 'Allocation and management of authentication information shall be controlled.',
    category: 'A5',
    priority: 'critical',
    evidence_types: ['policy', 'procedure', 'technical_control'],
    sort_order: 17,
    implementation_guidance: 'Implement strong password policy. Use MFA. Protect credential storage.',
  },
  {
    id: 'iso-A5.18',
    framework: 'iso27001',
    article_number: 'A.5.18',
    title: 'Access Rights',
    description: 'Access rights shall be provisioned, reviewed, modified, and removed in accordance with policy.',
    category: 'A5',
    priority: 'critical',
    evidence_types: ['procedure', 'access_review', 'technical_control'],
    sort_order: 18,
    implementation_guidance: 'Automate provisioning where possible. Conduct quarterly access reviews. Remove promptly on termination.',
  },
  {
    id: 'iso-A5.19',
    framework: 'iso27001',
    article_number: 'A.5.19',
    title: 'Information Security in Supplier Relationships',
    description: 'Processes and procedures for managing security risks in supplier relationships shall be defined.',
    category: 'A5',
    priority: 'high',
    evidence_types: ['policy', 'procedure', 'vendor_assessment'],
    sort_order: 19,
    implementation_guidance: 'Assess supplier security. Include security in procurement. Monitor supplier compliance.',
  },
  {
    id: 'iso-A5.20',
    framework: 'iso27001',
    article_number: 'A.5.20',
    title: 'Addressing Information Security Within Supplier Agreements',
    description: 'Relevant security requirements shall be established and agreed with each supplier.',
    category: 'A5',
    priority: 'high',
    evidence_types: ['contract', 'policy'],
    sort_order: 20,
    implementation_guidance: 'Include security clauses in contracts. Define SLAs. Require breach notification.',
  },
  {
    id: 'iso-A5.21',
    framework: 'iso27001',
    article_number: 'A.5.21',
    title: 'Managing Information Security in the ICT Supply Chain',
    description: 'Processes shall be defined for managing ICT supply chain security risks.',
    category: 'A5',
    priority: 'high',
    evidence_types: ['procedure', 'vendor_assessment', 'policy'],
    sort_order: 21,
    implementation_guidance: 'Map ICT supply chain. Assess subcontractor risks. Require security flow-down.',
  },
  {
    id: 'iso-A5.22',
    framework: 'iso27001',
    article_number: 'A.5.22',
    title: 'Monitoring, Review and Change Management of Supplier Services',
    description: 'Organization shall regularly monitor, review, and manage changes to supplier services.',
    category: 'A5',
    priority: 'high',
    evidence_types: ['procedure', 'monitoring_evidence', 'audit_report'],
    sort_order: 22,
    implementation_guidance: 'Review supplier performance. Monitor for security issues. Manage service changes.',
  },
  {
    id: 'iso-A5.23',
    framework: 'iso27001',
    article_number: 'A.5.23',
    title: 'Information Security for Use of Cloud Services',
    description: 'Processes for acquisition, use, management, and exit from cloud services shall be established.',
    category: 'A5',
    priority: 'high',
    evidence_types: ['policy', 'procedure', 'technical_control'],
    sort_order: 23,
    implementation_guidance: 'Define cloud security policy. Assess cloud providers. Implement cloud security controls.',
  },
  {
    id: 'iso-A5.24',
    framework: 'iso27001',
    article_number: 'A.5.24',
    title: 'Information Security Incident Management Planning and Preparation',
    description: 'Organization shall plan and prepare for managing information security incidents.',
    category: 'A5',
    priority: 'critical',
    evidence_types: ['procedure', 'policy', 'bcp_drp'],
    sort_order: 24,
    implementation_guidance: 'Document incident response plan. Define roles and responsibilities. Train incident team.',
  },
  {
    id: 'iso-A5.25',
    framework: 'iso27001',
    article_number: 'A.5.25',
    title: 'Assessment and Decision on Information Security Events',
    description: 'Information security events shall be assessed and decided whether to classify as incidents.',
    category: 'A5',
    priority: 'high',
    evidence_types: ['procedure', 'incident_log'],
    sort_order: 25,
    implementation_guidance: 'Define event classification criteria. Establish triage process. Document decisions.',
  },
  {
    id: 'iso-A5.26',
    framework: 'iso27001',
    article_number: 'A.5.26',
    title: 'Response to Information Security Incidents',
    description: 'Information security incidents shall be responded to in accordance with documented procedures.',
    category: 'A5',
    priority: 'critical',
    evidence_types: ['procedure', 'incident_log', 'technical_control'],
    sort_order: 26,
    implementation_guidance: 'Execute incident response procedures. Contain, eradicate, and recover. Document actions.',
  },
  {
    id: 'iso-A5.27',
    framework: 'iso27001',
    article_number: 'A.5.27',
    title: 'Learning from Information Security Incidents',
    description: 'Knowledge gained from incidents shall be used to strengthen and improve controls.',
    category: 'A5',
    priority: 'high',
    evidence_types: ['procedure', 'audit_report'],
    sort_order: 27,
    implementation_guidance: 'Conduct post-incident reviews. Document lessons learned. Update controls accordingly.',
  },
  {
    id: 'iso-A5.28',
    framework: 'iso27001',
    article_number: 'A.5.28',
    title: 'Collection of Evidence',
    description: 'Organization shall define and apply procedures for identification, collection, and preservation of evidence.',
    category: 'A5',
    priority: 'high',
    evidence_types: ['procedure', 'technical_control'],
    sort_order: 28,
    implementation_guidance: 'Document evidence handling procedures. Maintain chain of custody. Preserve forensic evidence.',
  },
  {
    id: 'iso-A5.29',
    framework: 'iso27001',
    article_number: 'A.5.29',
    title: 'Information Security During Disruption',
    description: 'Organization shall plan how to maintain information security during disruption.',
    category: 'A5',
    priority: 'high',
    evidence_types: ['bcp_drp', 'procedure'],
    sort_order: 29,
    implementation_guidance: 'Include security in BCP. Maintain security controls during disruption. Test scenarios.',
  },
  {
    id: 'iso-A5.30',
    framework: 'iso27001',
    article_number: 'A.5.30',
    title: 'ICT Readiness for Business Continuity',
    description: 'ICT readiness shall be planned, implemented, maintained, and tested based on business continuity objectives.',
    category: 'A5',
    priority: 'critical',
    evidence_types: ['bcp_drp', 'procedure', 'audit_report'],
    sort_order: 30,
    implementation_guidance: 'Define RTO/RPO. Implement redundancy. Test disaster recovery annually.',
  },
  {
    id: 'iso-A5.31',
    framework: 'iso27001',
    article_number: 'A.5.31',
    title: 'Legal, Statutory, Regulatory and Contractual Requirements',
    description: 'Legal, statutory, regulatory, and contractual requirements relevant to security shall be identified.',
    category: 'A5',
    priority: 'critical',
    evidence_types: ['policy', 'procedure', 'audit_report'],
    sort_order: 31,
    implementation_guidance: 'Maintain compliance register. Track regulatory changes. Conduct compliance assessments.',
  },
  {
    id: 'iso-A5.32',
    framework: 'iso27001',
    article_number: 'A.5.32',
    title: 'Intellectual Property Rights',
    description: 'Organization shall implement procedures to protect intellectual property rights.',
    category: 'A5',
    priority: 'medium',
    evidence_types: ['policy', 'procedure'],
    sort_order: 32,
    implementation_guidance: 'Track software licenses. Protect proprietary information. Document IP ownership.',
  },
  {
    id: 'iso-A5.33',
    framework: 'iso27001',
    article_number: 'A.5.33',
    title: 'Protection of Records',
    description: 'Records shall be protected from loss, destruction, falsification, and unauthorized access.',
    category: 'A5',
    priority: 'high',
    evidence_types: ['technical_control', 'procedure'],
    sort_order: 33,
    implementation_guidance: 'Implement record retention policy. Protect against unauthorized modification. Control destruction.',
  },
  {
    id: 'iso-A5.34',
    framework: 'iso27001',
    article_number: 'A.5.34',
    title: 'Privacy and Protection of PII',
    description: 'Organization shall identify and meet requirements for privacy and protection of PII.',
    category: 'A5',
    priority: 'critical',
    evidence_types: ['policy', 'procedure', 'technical_control'],
    sort_order: 34,
    implementation_guidance: 'Implement privacy program. Conduct DPIAs. Implement privacy-by-design.',
  },
  {
    id: 'iso-A5.35',
    framework: 'iso27001',
    article_number: 'A.5.35',
    title: 'Independent Review of Information Security',
    description: 'Approach to managing information security shall be independently reviewed at planned intervals.',
    category: 'A5',
    priority: 'high',
    evidence_types: ['audit_report', 'certification'],
    sort_order: 35,
    implementation_guidance: 'Conduct annual security audits. Engage external auditors. Act on findings.',
  },
  {
    id: 'iso-A5.36',
    framework: 'iso27001',
    article_number: 'A.5.36',
    title: 'Compliance with Policies, Rules and Standards',
    description: 'Compliance with security policies, rules, and standards shall be regularly reviewed.',
    category: 'A5',
    priority: 'high',
    evidence_types: ['audit_report', 'monitoring_evidence'],
    sort_order: 36,
    implementation_guidance: 'Implement compliance monitoring. Conduct internal audits. Track remediation.',
  },
  {
    id: 'iso-A5.37',
    framework: 'iso27001',
    article_number: 'A.5.37',
    title: 'Documented Operating Procedures',
    description: 'Operating procedures for information processing facilities shall be documented and available.',
    category: 'A5',
    priority: 'high',
    evidence_types: ['procedure', 'policy'],
    sort_order: 37,
    implementation_guidance: 'Document all operating procedures. Keep current and accessible. Review regularly.',
  },

  // ============================================================================
  // A.6 PEOPLE CONTROLS (8 controls)
  // ============================================================================
  {
    id: 'iso-A6.1',
    framework: 'iso27001',
    article_number: 'A.6.1',
    title: 'Screening',
    description: 'Background verification checks on candidates shall be carried out prior to employment.',
    category: 'A6',
    priority: 'high',
    evidence_types: ['procedure', 'policy'],
    sort_order: 40,
    implementation_guidance: 'Conduct background checks. Verify references. Check qualifications. Comply with privacy laws.',
  },
  {
    id: 'iso-A6.2',
    framework: 'iso27001',
    article_number: 'A.6.2',
    title: 'Terms and Conditions of Employment',
    description: 'Employment contracts shall state employees and organization responsibilities for security.',
    category: 'A6',
    priority: 'high',
    evidence_types: ['contract', 'policy'],
    sort_order: 41,
    implementation_guidance: 'Include security clauses in contracts. Reference acceptable use policy. Define confidentiality obligations.',
  },
  {
    id: 'iso-A6.3',
    framework: 'iso27001',
    article_number: 'A.6.3',
    title: 'Information Security Awareness, Education and Training',
    description: 'Personnel shall receive appropriate security awareness education and training.',
    category: 'A6',
    priority: 'critical',
    evidence_types: ['training_records', 'procedure'],
    sort_order: 42,
    implementation_guidance: 'Implement security awareness program. Provide role-specific training. Track completion.',
  },
  {
    id: 'iso-A6.4',
    framework: 'iso27001',
    article_number: 'A.6.4',
    title: 'Disciplinary Process',
    description: 'A disciplinary process shall be formalized for personnel who have committed security violations.',
    category: 'A6',
    priority: 'high',
    evidence_types: ['policy', 'procedure'],
    sort_order: 43,
    implementation_guidance: 'Document disciplinary process. Apply consistently. Coordinate with HR and legal.',
  },
  {
    id: 'iso-A6.5',
    framework: 'iso27001',
    article_number: 'A.6.5',
    title: 'Responsibilities After Termination or Change of Employment',
    description: 'Security responsibilities that remain valid after termination shall be defined and enforced.',
    category: 'A6',
    priority: 'high',
    evidence_types: ['contract', 'procedure'],
    sort_order: 44,
    implementation_guidance: 'Include post-employment clauses. Brief leavers on ongoing obligations. NDA requirements.',
  },
  {
    id: 'iso-A6.6',
    framework: 'iso27001',
    article_number: 'A.6.6',
    title: 'Confidentiality or Non-Disclosure Agreements',
    description: 'Confidentiality agreements reflecting security needs shall be identified and documented.',
    category: 'A6',
    priority: 'high',
    evidence_types: ['contract', 'policy'],
    sort_order: 45,
    implementation_guidance: 'Use NDAs for employees and contractors. Update as roles change. Include third parties.',
  },
  {
    id: 'iso-A6.7',
    framework: 'iso27001',
    article_number: 'A.6.7',
    title: 'Remote Working',
    description: 'Security measures shall be implemented when personnel are working remotely.',
    category: 'A6',
    priority: 'high',
    evidence_types: ['policy', 'technical_control', 'procedure'],
    sort_order: 46,
    implementation_guidance: 'Document remote work policy. Implement VPN. Secure home networks. Protect devices.',
  },
  {
    id: 'iso-A6.8',
    framework: 'iso27001',
    article_number: 'A.6.8',
    title: 'Information Security Event Reporting',
    description: 'Personnel shall report observed or suspected security events through appropriate channels.',
    category: 'A6',
    priority: 'high',
    evidence_types: ['procedure', 'technical_control', 'training_records'],
    sort_order: 47,
    implementation_guidance: 'Establish reporting channels. Train staff on what to report. Track reported events.',
  },

  // ============================================================================
  // A.7 PHYSICAL CONTROLS (14 controls)
  // ============================================================================
  {
    id: 'iso-A7.1',
    framework: 'iso27001',
    article_number: 'A.7.1',
    title: 'Physical Security Perimeters',
    description: 'Security perimeters shall be defined and used to protect areas containing information assets.',
    category: 'A7',
    priority: 'high',
    evidence_types: ['technical_control', 'observation'],
    sort_order: 50,
    implementation_guidance: 'Define secure areas. Implement physical barriers. Control entry points.',
  },
  {
    id: 'iso-A7.2',
    framework: 'iso27001',
    article_number: 'A.7.2',
    title: 'Physical Entry',
    description: 'Secure areas shall be protected by appropriate entry controls.',
    category: 'A7',
    priority: 'high',
    evidence_types: ['technical_control', 'procedure', 'observation'],
    sort_order: 51,
    implementation_guidance: 'Implement access cards/badges. Log all access. Escort visitors.',
  },
  {
    id: 'iso-A7.3',
    framework: 'iso27001',
    article_number: 'A.7.3',
    title: 'Securing Offices, Rooms and Facilities',
    description: 'Physical security for offices, rooms, and facilities shall be designed and implemented.',
    category: 'A7',
    priority: 'high',
    evidence_types: ['technical_control', 'observation'],
    sort_order: 52,
    implementation_guidance: 'Lock sensitive areas. Secure server rooms. Protect against environmental threats.',
  },
  {
    id: 'iso-A7.4',
    framework: 'iso27001',
    article_number: 'A.7.4',
    title: 'Physical Security Monitoring',
    description: 'Premises shall be continuously monitored for unauthorized physical access.',
    category: 'A7',
    priority: 'high',
    evidence_types: ['technical_control', 'monitoring_evidence'],
    sort_order: 53,
    implementation_guidance: 'Install CCTV. Implement intrusion detection. Monitor 24/7.',
  },
  {
    id: 'iso-A7.5',
    framework: 'iso27001',
    article_number: 'A.7.5',
    title: 'Protecting Against Physical and Environmental Threats',
    description: 'Protection against physical and environmental threats shall be designed and implemented.',
    category: 'A7',
    priority: 'high',
    evidence_types: ['technical_control', 'procedure'],
    sort_order: 54,
    implementation_guidance: 'Assess natural disaster risks. Implement fire suppression. Protect against flooding.',
  },
  {
    id: 'iso-A7.6',
    framework: 'iso27001',
    article_number: 'A.7.6',
    title: 'Working in Secure Areas',
    description: 'Security measures for working in secure areas shall be designed and implemented.',
    category: 'A7',
    priority: 'medium',
    evidence_types: ['procedure', 'observation'],
    sort_order: 55,
    implementation_guidance: 'Control access to secure areas. Prohibit recording devices. Supervise work.',
  },
  {
    id: 'iso-A7.7',
    framework: 'iso27001',
    article_number: 'A.7.7',
    title: 'Clear Desk and Clear Screen',
    description: 'Rules about clear desk and clear screen shall be defined and enforced.',
    category: 'A7',
    priority: 'medium',
    evidence_types: ['policy', 'observation'],
    sort_order: 56,
    implementation_guidance: 'Document clear desk policy. Lock screens when away. Secure documents.',
  },
  {
    id: 'iso-A7.8',
    framework: 'iso27001',
    article_number: 'A.7.8',
    title: 'Equipment Siting and Protection',
    description: 'Equipment shall be sited and protected to reduce risks from environmental threats.',
    category: 'A7',
    priority: 'high',
    evidence_types: ['technical_control', 'observation'],
    sort_order: 57,
    implementation_guidance: 'Position equipment away from threats. Use UPS. Control environmental conditions.',
  },
  {
    id: 'iso-A7.9',
    framework: 'iso27001',
    article_number: 'A.7.9',
    title: 'Security of Assets Off-Premises',
    description: 'Off-site assets shall be protected.',
    category: 'A7',
    priority: 'high',
    evidence_types: ['policy', 'procedure', 'technical_control'],
    sort_order: 58,
    implementation_guidance: 'Encrypt mobile devices. Implement remote wipe. Train on securing assets.',
  },
  {
    id: 'iso-A7.10',
    framework: 'iso27001',
    article_number: 'A.7.10',
    title: 'Storage Media',
    description: 'Storage media shall be managed through their lifecycle including acquisition, use, and disposal.',
    category: 'A7',
    priority: 'high',
    evidence_types: ['procedure', 'technical_control'],
    sort_order: 59,
    implementation_guidance: 'Control media usage. Encrypt removable media. Securely destroy when disposed.',
  },
  {
    id: 'iso-A7.11',
    framework: 'iso27001',
    article_number: 'A.7.11',
    title: 'Supporting Utilities',
    description: 'Information processing facilities shall be protected from power failures and other disruptions.',
    category: 'A7',
    priority: 'high',
    evidence_types: ['technical_control', 'procedure'],
    sort_order: 60,
    implementation_guidance: 'Implement UPS. Have backup power. Maintain utility infrastructure.',
  },
  {
    id: 'iso-A7.12',
    framework: 'iso27001',
    article_number: 'A.7.12',
    title: 'Cabling Security',
    description: 'Cables carrying power and data shall be protected from interception and damage.',
    category: 'A7',
    priority: 'medium',
    evidence_types: ['technical_control', 'observation'],
    sort_order: 61,
    implementation_guidance: 'Protect cable routes. Use conduits. Separate power and data cables.',
  },
  {
    id: 'iso-A7.13',
    framework: 'iso27001',
    article_number: 'A.7.13',
    title: 'Equipment Maintenance',
    description: 'Equipment shall be maintained correctly to ensure availability and integrity.',
    category: 'A7',
    priority: 'medium',
    evidence_types: ['procedure', 'monitoring_evidence'],
    sort_order: 62,
    implementation_guidance: 'Schedule preventive maintenance. Use authorized personnel. Maintain records.',
  },
  {
    id: 'iso-A7.14',
    framework: 'iso27001',
    article_number: 'A.7.14',
    title: 'Secure Disposal or Re-use of Equipment',
    description: 'Items containing storage media shall be verified to ensure data is removed before disposal.',
    category: 'A7',
    priority: 'high',
    evidence_types: ['procedure', 'observation'],
    sort_order: 63,
    implementation_guidance: 'Sanitize media before disposal. Use certified destruction. Document destruction.',
  },

  // ============================================================================
  // A.8 TECHNOLOGICAL CONTROLS (34 controls)
  // ============================================================================
  {
    id: 'iso-A8.1',
    framework: 'iso27001',
    article_number: 'A.8.1',
    title: 'User Endpoint Devices',
    description: 'Information stored on, processed by, or accessible via endpoint devices shall be protected.',
    category: 'A8',
    priority: 'critical',
    evidence_types: ['technical_control', 'policy'],
    sort_order: 70,
    implementation_guidance: 'Implement MDM. Require encryption. Deploy EDR. Manage patching.',
  },
  {
    id: 'iso-A8.2',
    framework: 'iso27001',
    article_number: 'A.8.2',
    title: 'Privileged Access Rights',
    description: 'Allocation and use of privileged access rights shall be restricted and managed.',
    category: 'A8',
    priority: 'critical',
    evidence_types: ['technical_control', 'procedure', 'access_review'],
    sort_order: 71,
    implementation_guidance: 'Implement PAM. Use just-in-time access. Monitor privileged activities.',
  },
  {
    id: 'iso-A8.3',
    framework: 'iso27001',
    article_number: 'A.8.3',
    title: 'Information Access Restriction',
    description: 'Access to information and application system functions shall be restricted in accordance with policy.',
    category: 'A8',
    priority: 'critical',
    evidence_types: ['technical_control', 'access_review'],
    sort_order: 72,
    implementation_guidance: 'Implement RBAC. Control access at application level. Restrict data access.',
  },
  {
    id: 'iso-A8.4',
    framework: 'iso27001',
    article_number: 'A.8.4',
    title: 'Access to Source Code',
    description: 'Read and write access to source code, development tools, and libraries shall be managed.',
    category: 'A8',
    priority: 'high',
    evidence_types: ['technical_control', 'procedure', 'access_review'],
    sort_order: 73,
    implementation_guidance: 'Control repository access. Use branch protection. Require code review.',
  },
  {
    id: 'iso-A8.5',
    framework: 'iso27001',
    article_number: 'A.8.5',
    title: 'Secure Authentication',
    description: 'Secure authentication technologies and procedures shall be implemented.',
    category: 'A8',
    priority: 'critical',
    evidence_types: ['technical_control', 'policy'],
    sort_order: 74,
    implementation_guidance: 'Implement MFA. Use secure protocols. Protect credential transmission.',
  },
  {
    id: 'iso-A8.6',
    framework: 'iso27001',
    article_number: 'A.8.6',
    title: 'Capacity Management',
    description: 'Resource use shall be monitored and adjustments made to meet capacity requirements.',
    category: 'A8',
    priority: 'medium',
    evidence_types: ['monitoring_evidence', 'procedure'],
    sort_order: 75,
    implementation_guidance: 'Monitor resource usage. Plan capacity. Implement auto-scaling where appropriate.',
  },
  {
    id: 'iso-A8.7',
    framework: 'iso27001',
    article_number: 'A.8.7',
    title: 'Protection Against Malware',
    description: 'Protection against malware shall be implemented and supported by appropriate awareness.',
    category: 'A8',
    priority: 'critical',
    evidence_types: ['technical_control', 'monitoring_evidence'],
    sort_order: 76,
    implementation_guidance: 'Deploy anti-malware. Keep signatures updated. Train users on threats.',
  },
  {
    id: 'iso-A8.8',
    framework: 'iso27001',
    article_number: 'A.8.8',
    title: 'Management of Technical Vulnerabilities',
    description: 'Information about vulnerabilities shall be obtained, exposure evaluated, and measures taken.',
    category: 'A8',
    priority: 'critical',
    evidence_types: ['vulnerability_scan', 'procedure', 'technical_control'],
    sort_order: 77,
    implementation_guidance: 'Implement vulnerability management. Scan regularly. Patch within SLAs.',
  },
  {
    id: 'iso-A8.9',
    framework: 'iso27001',
    article_number: 'A.8.9',
    title: 'Configuration Management',
    description: 'Configurations including security configurations shall be established, documented, and managed.',
    category: 'A8',
    priority: 'high',
    evidence_types: ['technical_control', 'procedure'],
    sort_order: 78,
    implementation_guidance: 'Document baseline configurations. Implement hardening standards. Monitor for drift.',
  },
  {
    id: 'iso-A8.10',
    framework: 'iso27001',
    article_number: 'A.8.10',
    title: 'Information Deletion',
    description: 'Information stored in systems and devices shall be deleted when no longer required.',
    category: 'A8',
    priority: 'high',
    evidence_types: ['procedure', 'technical_control'],
    sort_order: 79,
    implementation_guidance: 'Implement retention policies. Automate deletion. Verify deletion is complete.',
  },
  {
    id: 'iso-A8.11',
    framework: 'iso27001',
    article_number: 'A.8.11',
    title: 'Data Masking',
    description: 'Data masking shall be used in accordance with policy on access control and business requirements.',
    category: 'A8',
    priority: 'high',
    evidence_types: ['technical_control', 'procedure'],
    sort_order: 80,
    implementation_guidance: 'Mask data in non-production. Implement dynamic data masking. Protect sensitive fields.',
  },
  {
    id: 'iso-A8.12',
    framework: 'iso27001',
    article_number: 'A.8.12',
    title: 'Data Leakage Prevention',
    description: 'Data leakage prevention measures shall be applied to systems, networks, and endpoints.',
    category: 'A8',
    priority: 'high',
    evidence_types: ['technical_control', 'monitoring_evidence'],
    sort_order: 81,
    implementation_guidance: 'Implement DLP solution. Monitor data movement. Block unauthorized transfers.',
  },
  {
    id: 'iso-A8.13',
    framework: 'iso27001',
    article_number: 'A.8.13',
    title: 'Information Backup',
    description: 'Backup copies of information, software, and systems shall be maintained and tested.',
    category: 'A8',
    priority: 'critical',
    evidence_types: ['technical_control', 'procedure', 'monitoring_evidence'],
    sort_order: 82,
    implementation_guidance: 'Implement backup strategy. Store offsite. Test restores regularly.',
  },
  {
    id: 'iso-A8.14',
    framework: 'iso27001',
    article_number: 'A.8.14',
    title: 'Redundancy of Information Processing Facilities',
    description: 'Information processing facilities shall have sufficient redundancy to meet availability requirements.',
    category: 'A8',
    priority: 'high',
    evidence_types: ['technical_control', 'network_diagram'],
    sort_order: 83,
    implementation_guidance: 'Implement HA architecture. Use multiple availability zones. Automate failover.',
  },
  {
    id: 'iso-A8.15',
    framework: 'iso27001',
    article_number: 'A.8.15',
    title: 'Logging',
    description: 'Logs that record activities, exceptions, faults, and events shall be produced and protected.',
    category: 'A8',
    priority: 'critical',
    evidence_types: ['technical_control', 'monitoring_evidence'],
    sort_order: 84,
    implementation_guidance: 'Implement centralized logging. Capture security events. Protect log integrity.',
  },
  {
    id: 'iso-A8.16',
    framework: 'iso27001',
    article_number: 'A.8.16',
    title: 'Monitoring Activities',
    description: 'Networks, systems, and applications shall be monitored for anomalous behavior.',
    category: 'A8',
    priority: 'critical',
    evidence_types: ['technical_control', 'monitoring_evidence'],
    sort_order: 85,
    implementation_guidance: 'Deploy SIEM. Define monitoring use cases. Alert on anomalies.',
  },
  {
    id: 'iso-A8.17',
    framework: 'iso27001',
    article_number: 'A.8.17',
    title: 'Clock Synchronization',
    description: 'Clocks of information processing systems shall be synchronized to approved time sources.',
    category: 'A8',
    priority: 'medium',
    evidence_types: ['technical_control'],
    sort_order: 86,
    implementation_guidance: 'Implement NTP. Use multiple time sources. Monitor synchronization.',
  },
  {
    id: 'iso-A8.18',
    framework: 'iso27001',
    article_number: 'A.8.18',
    title: 'Use of Privileged Utility Programs',
    description: 'Use of utility programs capable of overriding controls shall be restricted and controlled.',
    category: 'A8',
    priority: 'high',
    evidence_types: ['technical_control', 'procedure'],
    sort_order: 87,
    implementation_guidance: 'Restrict admin tools. Log usage. Require authorization.',
  },
  {
    id: 'iso-A8.19',
    framework: 'iso27001',
    article_number: 'A.8.19',
    title: 'Installation of Software on Operational Systems',
    description: 'Procedures and measures shall be implemented to securely manage software installation.',
    category: 'A8',
    priority: 'high',
    evidence_types: ['procedure', 'technical_control'],
    sort_order: 88,
    implementation_guidance: 'Control software installation. Use application whitelisting. Test before deployment.',
  },
  {
    id: 'iso-A8.20',
    framework: 'iso27001',
    article_number: 'A.8.20',
    title: 'Networks Security',
    description: 'Networks and network devices shall be secured, managed, and controlled.',
    category: 'A8',
    priority: 'critical',
    evidence_types: ['technical_control', 'network_diagram'],
    sort_order: 89,
    implementation_guidance: 'Implement firewalls. Segment networks. Monitor traffic. Harden devices.',
  },
  {
    id: 'iso-A8.21',
    framework: 'iso27001',
    article_number: 'A.8.21',
    title: 'Security of Network Services',
    description: 'Security mechanisms, service levels, and requirements shall be identified and included in agreements.',
    category: 'A8',
    priority: 'high',
    evidence_types: ['contract', 'technical_control'],
    sort_order: 90,
    implementation_guidance: 'Define security SLAs. Include in contracts. Monitor provider compliance.',
  },
  {
    id: 'iso-A8.22',
    framework: 'iso27001',
    article_number: 'A.8.22',
    title: 'Segregation of Networks',
    description: 'Groups of information services, users, and systems shall be segregated in networks.',
    category: 'A8',
    priority: 'high',
    evidence_types: ['technical_control', 'network_diagram'],
    sort_order: 91,
    implementation_guidance: 'Implement VLANs. Use micro-segmentation. Control inter-segment traffic.',
  },
  {
    id: 'iso-A8.23',
    framework: 'iso27001',
    article_number: 'A.8.23',
    title: 'Web Filtering',
    description: 'Access to external websites shall be managed to reduce exposure to malicious content.',
    category: 'A8',
    priority: 'medium',
    evidence_types: ['technical_control', 'policy'],
    sort_order: 92,
    implementation_guidance: 'Implement web proxy. Block malicious categories. Monitor web access.',
  },
  {
    id: 'iso-A8.24',
    framework: 'iso27001',
    article_number: 'A.8.24',
    title: 'Use of Cryptography',
    description: 'Rules for effective use of cryptography shall be defined and implemented.',
    category: 'A8',
    priority: 'critical',
    evidence_types: ['policy', 'technical_control', 'encryption_config'],
    sort_order: 93,
    implementation_guidance: 'Document cryptography policy. Use strong algorithms. Manage keys properly.',
  },
  {
    id: 'iso-A8.25',
    framework: 'iso27001',
    article_number: 'A.8.25',
    title: 'Secure Development Life Cycle',
    description: 'Rules for secure development shall be established and applied.',
    category: 'A8',
    priority: 'high',
    evidence_types: ['procedure', 'technical_control'],
    sort_order: 94,
    implementation_guidance: 'Implement secure SDLC. Include security testing. Train developers.',
  },
  {
    id: 'iso-A8.26',
    framework: 'iso27001',
    article_number: 'A.8.26',
    title: 'Application Security Requirements',
    description: 'Security requirements shall be identified and specified when developing or acquiring applications.',
    category: 'A8',
    priority: 'high',
    evidence_types: ['procedure', 'risk_assessment'],
    sort_order: 95,
    implementation_guidance: 'Define security requirements early. Include in RFPs. Verify implementation.',
  },
  {
    id: 'iso-A8.27',
    framework: 'iso27001',
    article_number: 'A.8.27',
    title: 'Secure System Architecture and Engineering Principles',
    description: 'Principles for engineering secure systems shall be established and applied.',
    category: 'A8',
    priority: 'high',
    evidence_types: ['procedure', 'policy'],
    sort_order: 96,
    implementation_guidance: 'Document architecture principles. Follow security patterns. Review designs.',
  },
  {
    id: 'iso-A8.28',
    framework: 'iso27001',
    article_number: 'A.8.28',
    title: 'Secure Coding',
    description: 'Secure coding principles shall be applied to software development.',
    category: 'A8',
    priority: 'high',
    evidence_types: ['procedure', 'technical_control'],
    sort_order: 97,
    implementation_guidance: 'Use secure coding standards. Implement SAST. Train developers.',
  },
  {
    id: 'iso-A8.29',
    framework: 'iso27001',
    article_number: 'A.8.29',
    title: 'Security Testing in Development and Acceptance',
    description: 'Security testing processes shall be defined and implemented in development lifecycle.',
    category: 'A8',
    priority: 'high',
    evidence_types: ['penetration_test', 'procedure', 'technical_control'],
    sort_order: 98,
    implementation_guidance: 'Include security in testing. Perform DAST. Test before production.',
  },
  {
    id: 'iso-A8.30',
    framework: 'iso27001',
    article_number: 'A.8.30',
    title: 'Outsourced Development',
    description: 'Organization shall direct, monitor, and review outsourced system development.',
    category: 'A8',
    priority: 'high',
    evidence_types: ['contract', 'procedure', 'audit_report'],
    sort_order: 99,
    implementation_guidance: 'Include security requirements. Review deliverables. Conduct security assessments.',
  },
  {
    id: 'iso-A8.31',
    framework: 'iso27001',
    article_number: 'A.8.31',
    title: 'Separation of Development, Test and Production Environments',
    description: 'Development, testing, and production environments shall be separated and secured.',
    category: 'A8',
    priority: 'high',
    evidence_types: ['technical_control', 'observation'],
    sort_order: 100,
    implementation_guidance: 'Separate environments. Control access. Mask production data in lower environments.',
  },
  {
    id: 'iso-A8.32',
    framework: 'iso27001',
    article_number: 'A.8.32',
    title: 'Change Management',
    description: 'Changes to information processing facilities and systems shall be subject to change management.',
    category: 'A8',
    priority: 'high',
    evidence_types: ['procedure', 'monitoring_evidence'],
    sort_order: 101,
    implementation_guidance: 'Document change procedures. Require approvals. Track all changes.',
  },
  {
    id: 'iso-A8.33',
    framework: 'iso27001',
    article_number: 'A.8.33',
    title: 'Test Information',
    description: 'Test information shall be appropriately selected, protected, and managed.',
    category: 'A8',
    priority: 'medium',
    evidence_types: ['procedure', 'technical_control'],
    sort_order: 102,
    implementation_guidance: 'Use synthetic test data. Mask sensitive data. Protect test databases.',
  },
  {
    id: 'iso-A8.34',
    framework: 'iso27001',
    article_number: 'A.8.34',
    title: 'Protection of Information Systems During Audit Testing',
    description: 'Audit tests and other activities involving assessment of systems shall be planned and agreed.',
    category: 'A8',
    priority: 'medium',
    evidence_types: ['procedure', 'policy'],
    sort_order: 103,
    implementation_guidance: 'Plan audit activities. Minimize operational impact. Protect audit data.',
  },
];

export const ISO27001_REQUIREMENT_COUNT = ISO27001_REQUIREMENTS.length;

export function getISO27001RequirementsByCategory(category: string): FrameworkRequirement[] {
  return ISO27001_REQUIREMENTS.filter(r => r.category === category);
}

export function getISO27001RequirementById(id: string): FrameworkRequirement | undefined {
  return ISO27001_REQUIREMENTS.find(r => r.id === id);
}

export function getISO27001CriticalRequirements(): FrameworkRequirement[] {
  return ISO27001_REQUIREMENTS.filter(r => r.priority === 'critical');
}

export function getISO27001ControlsByAnnex(): Record<string, FrameworkRequirement[]> {
  return {
    'A5': getISO27001RequirementsByCategory('A5'),
    'A6': getISO27001RequirementsByCategory('A6'),
    'A7': getISO27001RequirementsByCategory('A7'),
    'A8': getISO27001RequirementsByCategory('A8'),
  };
}
