/**
 * NIS2 Directive Requirements
 *
 * Network and Information Security Directive 2 (EU 2022/2555)
 * Covers Articles 20-36 with focus on cybersecurity risk management measures (Article 21)
 */

import { FrameworkRequirement } from './framework-types';

export const NIS2_REQUIREMENTS: FrameworkRequirement[] = [
  // ============================================================================
  // GOVERNANCE (Article 20)
  // ============================================================================
  {
    id: 'nis2-20-1',
    framework: 'nis2',
    article_number: 'Art.20(1)',
    title: 'Management Body Accountability',
    description: 'Management bodies of essential and important entities must approve cybersecurity risk-management measures and oversee their implementation. Members can be held liable for infringements.',
    category: 'governance',
    priority: 'critical',
    evidence_types: ['policy', 'procedure', 'interview', 'audit_report'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 1,
    implementation_guidance: 'Ensure board-level approval of cybersecurity policies. Document management oversight activities and decisions.',
    regulatory_reference: 'NIS2 Directive Article 20(1)',
  },
  {
    id: 'nis2-20-2',
    framework: 'nis2',
    article_number: 'Art.20(2)',
    title: 'Management Body Training',
    description: 'Members of management bodies must follow training to gain sufficient knowledge and skills to identify risks, assess cybersecurity practices, and understand their impact on services.',
    category: 'governance',
    priority: 'high',
    evidence_types: ['training_records', 'certification', 'interview'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 2,
    implementation_guidance: 'Implement mandatory cybersecurity training for all board members. Track completion and refresh periodically.',
    regulatory_reference: 'NIS2 Directive Article 20(2)',
  },
  {
    id: 'nis2-20-3',
    framework: 'nis2',
    article_number: 'Art.20(3)',
    title: 'Employee Training Programs',
    description: 'Entities shall encourage essential and important entities to offer similar training to their employees on a regular basis.',
    category: 'governance',
    priority: 'medium',
    evidence_types: ['training_records', 'procedure', 'policy'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 3,
    implementation_guidance: 'Establish regular cybersecurity awareness training for all employees. Track participation rates.',
    regulatory_reference: 'NIS2 Directive Article 20(3)',
  },

  // ============================================================================
  // RISK MANAGEMENT MEASURES (Article 21)
  // ============================================================================
  {
    id: 'nis2-21-1',
    framework: 'nis2',
    article_number: 'Art.21(1)',
    title: 'All-Hazards Approach',
    description: 'Take appropriate and proportionate technical, operational and organizational measures to manage risks posed to security of network and information systems, following an all-hazards approach.',
    category: 'risk_management',
    priority: 'critical',
    evidence_types: ['policy', 'risk_assessment', 'procedure'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 10,
    implementation_guidance: 'Implement comprehensive risk management framework covering all threat types including cyber, physical, and environmental.',
    regulatory_reference: 'NIS2 Directive Article 21(1)',
  },
  {
    id: 'nis2-21-2a',
    framework: 'nis2',
    article_number: 'Art.21(2)(a)',
    title: 'Policies on Risk Analysis and Information System Security',
    description: 'Policies on risk analysis and information system security including risk assessment methodologies and security policies.',
    category: 'risk_management',
    priority: 'critical',
    evidence_types: ['policy', 'risk_assessment', 'procedure'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 11,
    implementation_guidance: 'Document comprehensive information security policy. Conduct regular risk assessments using established methodology.',
    regulatory_reference: 'NIS2 Directive Article 21(2)(a)',
  },
  {
    id: 'nis2-21-2b',
    framework: 'nis2',
    article_number: 'Art.21(2)(b)',
    title: 'Incident Handling',
    description: 'Incident handling procedures including detection, analysis, containment, eradication, and recovery.',
    category: 'incident_handling',
    priority: 'critical',
    evidence_types: ['procedure', 'incident_log', 'technical_control'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 12,
    implementation_guidance: 'Establish incident response plan with defined roles, escalation procedures, and communication protocols.',
    regulatory_reference: 'NIS2 Directive Article 21(2)(b)',
  },
  {
    id: 'nis2-21-2c',
    framework: 'nis2',
    article_number: 'Art.21(2)(c)',
    title: 'Business Continuity and Crisis Management',
    description: 'Business continuity management including backup management, disaster recovery, and crisis management.',
    category: 'business_continuity',
    priority: 'critical',
    evidence_types: ['bcp_drp', 'procedure', 'technical_control', 'audit_report'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 13,
    implementation_guidance: 'Develop BCP/DRP with documented recovery objectives. Test plans annually and after significant changes.',
    regulatory_reference: 'NIS2 Directive Article 21(2)(c)',
  },
  {
    id: 'nis2-21-2d',
    framework: 'nis2',
    article_number: 'Art.21(2)(d)',
    title: 'Supply Chain Security',
    description: 'Supply chain security including security-related aspects concerning relationships between each entity and its direct suppliers or service providers.',
    category: 'supply_chain',
    priority: 'critical',
    evidence_types: ['vendor_assessment', 'contract', 'policy', 'procedure'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 14,
    implementation_guidance: 'Implement vendor risk management program. Include security requirements in contracts. Conduct regular assessments.',
    regulatory_reference: 'NIS2 Directive Article 21(2)(d)',
  },
  {
    id: 'nis2-21-2e',
    framework: 'nis2',
    article_number: 'Art.21(2)(e)',
    title: 'Security in Network and Information Systems',
    description: 'Security in network and information systems acquisition, development and maintenance, including vulnerability handling and disclosure.',
    category: 'risk_management',
    priority: 'high',
    evidence_types: ['procedure', 'vulnerability_scan', 'technical_control'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 15,
    implementation_guidance: 'Integrate security into SDLC. Implement vulnerability management program with regular scanning and patching.',
    regulatory_reference: 'NIS2 Directive Article 21(2)(e)',
  },
  {
    id: 'nis2-21-2f',
    framework: 'nis2',
    article_number: 'Art.21(2)(f)',
    title: 'Cybersecurity Measure Assessment',
    description: 'Policies and procedures to assess the effectiveness of cybersecurity risk-management measures.',
    category: 'risk_management',
    priority: 'high',
    evidence_types: ['audit_report', 'procedure', 'penetration_test'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 16,
    implementation_guidance: 'Conduct regular security assessments and penetration tests. Document findings and track remediation.',
    regulatory_reference: 'NIS2 Directive Article 21(2)(f)',
  },
  {
    id: 'nis2-21-2g',
    framework: 'nis2',
    article_number: 'Art.21(2)(g)',
    title: 'Basic Cyber Hygiene Practices',
    description: 'Basic cyber hygiene practices and cybersecurity training for all staff.',
    category: 'risk_management',
    priority: 'high',
    evidence_types: ['training_records', 'policy', 'procedure'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 17,
    implementation_guidance: 'Implement security awareness program. Cover phishing, password hygiene, physical security, and social engineering.',
    regulatory_reference: 'NIS2 Directive Article 21(2)(g)',
  },
  {
    id: 'nis2-21-2h',
    framework: 'nis2',
    article_number: 'Art.21(2)(h)',
    title: 'Cryptography and Encryption',
    description: 'Policies and procedures regarding the use of cryptography and, where appropriate, encryption.',
    category: 'risk_management',
    priority: 'high',
    evidence_types: ['policy', 'technical_control', 'encryption_config'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 18,
    implementation_guidance: 'Document cryptography policy. Use strong encryption for data at rest and in transit. Manage keys securely.',
    regulatory_reference: 'NIS2 Directive Article 21(2)(h)',
  },
  {
    id: 'nis2-21-2i',
    framework: 'nis2',
    article_number: 'Art.21(2)(i)',
    title: 'Human Resources Security',
    description: 'Human resources security, access control policies and asset management.',
    category: 'risk_management',
    priority: 'high',
    evidence_types: ['policy', 'procedure', 'access_review', 'technical_control'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 19,
    implementation_guidance: 'Implement HR security controls including background checks, access provisioning/deprovisioning, and asset tracking.',
    regulatory_reference: 'NIS2 Directive Article 21(2)(i)',
  },
  {
    id: 'nis2-21-2j',
    framework: 'nis2',
    article_number: 'Art.21(2)(j)',
    title: 'Multi-Factor Authentication',
    description: 'Use of multi-factor authentication or continuous authentication solutions, secured voice, video and text communications.',
    category: 'risk_management',
    priority: 'high',
    evidence_types: ['technical_control', 'policy', 'encryption_config'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 20,
    implementation_guidance: 'Implement MFA for all critical systems and remote access. Use secure communication channels.',
    regulatory_reference: 'NIS2 Directive Article 21(2)(j)',
  },
  {
    id: 'nis2-21-3',
    framework: 'nis2',
    article_number: 'Art.21(3)',
    title: 'Proportionality Assessment',
    description: 'When assessing appropriateness of measures, account shall be taken of degree of exposure to risks, size of entity, implementation costs, and likelihood and severity of incidents.',
    category: 'risk_management',
    priority: 'medium',
    evidence_types: ['risk_assessment', 'procedure'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 21,
    implementation_guidance: 'Document risk-based approach to security controls. Consider cost-benefit analysis for security investments.',
    regulatory_reference: 'NIS2 Directive Article 21(3)',
  },
  {
    id: 'nis2-21-4',
    framework: 'nis2',
    article_number: 'Art.21(4)',
    title: 'European and International Standards',
    description: 'Member States shall ensure that entities consider European and international standards and technical specifications relevant to network and information systems security.',
    category: 'risk_management',
    priority: 'medium',
    evidence_types: ['policy', 'certification', 'audit_report'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 22,
    implementation_guidance: 'Align security controls with ISO 27001, NIST CSF, or other recognized standards.',
    regulatory_reference: 'NIS2 Directive Article 21(4)',
  },

  // ============================================================================
  // REPORTING OBLIGATIONS (Article 23)
  // ============================================================================
  {
    id: 'nis2-23-1',
    framework: 'nis2',
    article_number: 'Art.23(1)',
    title: 'Significant Incident Notification',
    description: 'Each Member State shall ensure that essential and important entities notify significant incidents to their CSIRT or competent authority without undue delay.',
    category: 'reporting',
    priority: 'critical',
    evidence_types: ['procedure', 'incident_log', 'policy'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 30,
    implementation_guidance: 'Establish incident notification procedures with clear criteria for significant incidents and reporting timelines.',
    regulatory_reference: 'NIS2 Directive Article 23(1)',
  },
  {
    id: 'nis2-23-4a',
    framework: 'nis2',
    article_number: 'Art.23(4)(a)',
    title: 'Early Warning Notification (24h)',
    description: 'Early warning within 24 hours of becoming aware of significant incident, indicating if suspected to be caused by unlawful or malicious acts.',
    category: 'reporting',
    priority: 'critical',
    evidence_types: ['procedure', 'incident_log'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 31,
    implementation_guidance: 'Establish 24/7 incident detection capability with clear escalation to meet 24-hour notification requirement.',
    regulatory_reference: 'NIS2 Directive Article 23(4)(a)',
  },
  {
    id: 'nis2-23-4b',
    framework: 'nis2',
    article_number: 'Art.23(4)(b)',
    title: 'Incident Notification (72h)',
    description: 'Incident notification within 72 hours with initial assessment including severity, impact, and indicators of compromise where applicable.',
    category: 'reporting',
    priority: 'critical',
    evidence_types: ['procedure', 'incident_log'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 32,
    implementation_guidance: 'Develop incident assessment templates. Ensure capability to determine severity and impact within 72 hours.',
    regulatory_reference: 'NIS2 Directive Article 23(4)(b)',
  },
  {
    id: 'nis2-23-4c',
    framework: 'nis2',
    article_number: 'Art.23(4)(c)',
    title: 'Final Incident Report (1 month)',
    description: 'Final report within one month including detailed description of incident, severity, impact, type of threat, and applied/ongoing mitigation measures.',
    category: 'reporting',
    priority: 'high',
    evidence_types: ['procedure', 'incident_log', 'audit_report'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 33,
    implementation_guidance: 'Establish post-incident review process. Document lessons learned and remediation actions.',
    regulatory_reference: 'NIS2 Directive Article 23(4)(c)',
  },
  {
    id: 'nis2-23-5',
    framework: 'nis2',
    article_number: 'Art.23(5)',
    title: 'User/Customer Notification',
    description: 'Where appropriate, notify users/customers affected by significant cyber threats of measures they may take to mitigate risk.',
    category: 'reporting',
    priority: 'high',
    evidence_types: ['procedure', 'policy'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 34,
    implementation_guidance: 'Develop customer communication templates and procedures for threat notifications.',
    regulatory_reference: 'NIS2 Directive Article 23(5)',
  },

  // ============================================================================
  // ADDITIONAL RISK MANAGEMENT MEASURES
  // ============================================================================
  {
    id: 'nis2-rm-detection',
    framework: 'nis2',
    article_number: 'Art.21(2)(b)',
    title: 'Detection Capabilities',
    description: 'Implement detection capabilities to identify security events and incidents in a timely manner.',
    category: 'incident_handling',
    subcategory: 'detection',
    priority: 'high',
    evidence_types: ['technical_control', 'monitoring_evidence', 'procedure'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 40,
    implementation_guidance: 'Deploy SIEM, IDS/IPS, and endpoint detection solutions. Establish 24/7 monitoring capability.',
    regulatory_reference: 'NIS2 Directive Article 21(2)(b)',
  },
  {
    id: 'nis2-rm-analysis',
    framework: 'nis2',
    article_number: 'Art.21(2)(b)',
    title: 'Incident Analysis',
    description: 'Capability to analyze and investigate security incidents to determine root cause and impact.',
    category: 'incident_handling',
    subcategory: 'analysis',
    priority: 'high',
    evidence_types: ['procedure', 'technical_control', 'incident_log'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 41,
    implementation_guidance: 'Establish forensic capabilities. Document analysis procedures and maintain investigation logs.',
    regulatory_reference: 'NIS2 Directive Article 21(2)(b)',
  },
  {
    id: 'nis2-rm-containment',
    framework: 'nis2',
    article_number: 'Art.21(2)(b)',
    title: 'Incident Containment',
    description: 'Procedures and capabilities to contain security incidents and prevent further damage.',
    category: 'incident_handling',
    subcategory: 'containment',
    priority: 'high',
    evidence_types: ['procedure', 'technical_control'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 42,
    implementation_guidance: 'Define containment strategies for different incident types. Ensure ability to isolate affected systems.',
    regulatory_reference: 'NIS2 Directive Article 21(2)(b)',
  },
  {
    id: 'nis2-rm-recovery',
    framework: 'nis2',
    article_number: 'Art.21(2)(c)',
    title: 'System Recovery',
    description: 'Capability to recover systems and data following a security incident or disaster.',
    category: 'business_continuity',
    subcategory: 'recovery',
    priority: 'critical',
    evidence_types: ['bcp_drp', 'procedure', 'technical_control'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 43,
    implementation_guidance: 'Document recovery procedures. Test recovery capabilities regularly. Maintain offline backups.',
    regulatory_reference: 'NIS2 Directive Article 21(2)(c)',
  },
  {
    id: 'nis2-rm-backup',
    framework: 'nis2',
    article_number: 'Art.21(2)(c)',
    title: 'Backup Management',
    description: 'Implementation of backup procedures for critical data and systems.',
    category: 'business_continuity',
    subcategory: 'backup',
    priority: 'critical',
    evidence_types: ['procedure', 'technical_control', 'monitoring_evidence'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 44,
    implementation_guidance: 'Implement 3-2-1 backup strategy. Test restore procedures monthly. Encrypt backup data.',
    regulatory_reference: 'NIS2 Directive Article 21(2)(c)',
  },
  {
    id: 'nis2-rm-vendor-assess',
    framework: 'nis2',
    article_number: 'Art.21(2)(d)',
    title: 'Supplier Security Assessment',
    description: 'Assessment of security practices of direct suppliers and service providers.',
    category: 'supply_chain',
    subcategory: 'assessment',
    priority: 'high',
    evidence_types: ['vendor_assessment', 'soc2_report', 'questionnaire'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 45,
    implementation_guidance: 'Conduct security assessments for all critical suppliers. Review SOC 2 reports and certifications.',
    regulatory_reference: 'NIS2 Directive Article 21(2)(d)',
  },
  {
    id: 'nis2-rm-vendor-contract',
    framework: 'nis2',
    article_number: 'Art.21(2)(d)',
    title: 'Security Contractual Requirements',
    description: 'Inclusion of security requirements in contracts with suppliers and service providers.',
    category: 'supply_chain',
    subcategory: 'contracts',
    priority: 'high',
    evidence_types: ['contract', 'policy'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 46,
    implementation_guidance: 'Include security clauses in all vendor contracts. Require incident notification and audit rights.',
    regulatory_reference: 'NIS2 Directive Article 21(2)(d)',
  },
  {
    id: 'nis2-rm-secure-dev',
    framework: 'nis2',
    article_number: 'Art.21(2)(e)',
    title: 'Secure Development Practices',
    description: 'Security requirements in the development and maintenance of network and information systems.',
    category: 'risk_management',
    subcategory: 'development',
    priority: 'high',
    evidence_types: ['procedure', 'technical_control', 'audit_report'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 47,
    implementation_guidance: 'Implement secure SDLC. Conduct code reviews and security testing. Use dependency scanning.',
    regulatory_reference: 'NIS2 Directive Article 21(2)(e)',
  },
  {
    id: 'nis2-rm-vuln-mgmt',
    framework: 'nis2',
    article_number: 'Art.21(2)(e)',
    title: 'Vulnerability Management',
    description: 'Processes for vulnerability handling including identification, assessment, and remediation.',
    category: 'risk_management',
    subcategory: 'vulnerability',
    priority: 'high',
    evidence_types: ['vulnerability_scan', 'procedure', 'technical_control'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 48,
    implementation_guidance: 'Implement vulnerability scanning. Define SLAs for remediation based on severity. Track metrics.',
    regulatory_reference: 'NIS2 Directive Article 21(2)(e)',
  },
  {
    id: 'nis2-rm-network-sec',
    framework: 'nis2',
    article_number: 'Art.21(2)(a)',
    title: 'Network Security Controls',
    description: 'Implementation of network security controls including firewalls, network segmentation, and monitoring.',
    category: 'risk_management',
    subcategory: 'network',
    priority: 'high',
    evidence_types: ['technical_control', 'network_diagram', 'monitoring_evidence'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 49,
    implementation_guidance: 'Implement defense in depth. Segment networks based on sensitivity. Monitor network traffic.',
    regulatory_reference: 'NIS2 Directive Article 21(2)(a)',
  },
  {
    id: 'nis2-rm-endpoint',
    framework: 'nis2',
    article_number: 'Art.21(2)(a)',
    title: 'Endpoint Protection',
    description: 'Implementation of endpoint protection measures including EDR, antivirus, and device management.',
    category: 'risk_management',
    subcategory: 'endpoint',
    priority: 'high',
    evidence_types: ['technical_control', 'monitoring_evidence'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 50,
    implementation_guidance: 'Deploy EDR solution on all endpoints. Implement device encryption and remote wipe capability.',
    regulatory_reference: 'NIS2 Directive Article 21(2)(a)',
  },
  {
    id: 'nis2-rm-access-mgmt',
    framework: 'nis2',
    article_number: 'Art.21(2)(i)',
    title: 'Access Management',
    description: 'Implementation of access control including identity management, authentication, and authorization.',
    category: 'risk_management',
    subcategory: 'access',
    priority: 'high',
    evidence_types: ['policy', 'procedure', 'access_review', 'technical_control'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 51,
    implementation_guidance: 'Implement least privilege. Conduct quarterly access reviews. Use role-based access control.',
    regulatory_reference: 'NIS2 Directive Article 21(2)(i)',
  },
  {
    id: 'nis2-rm-privileged',
    framework: 'nis2',
    article_number: 'Art.21(2)(i)',
    title: 'Privileged Access Management',
    description: 'Special controls for privileged access including PAM solutions and enhanced monitoring.',
    category: 'risk_management',
    subcategory: 'privileged_access',
    priority: 'critical',
    evidence_types: ['technical_control', 'procedure', 'monitoring_evidence'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 52,
    implementation_guidance: 'Implement PAM solution. Use just-in-time access. Monitor and record privileged sessions.',
    regulatory_reference: 'NIS2 Directive Article 21(2)(i)',
  },

  // ============================================================================
  // SUPERVISION & ENFORCEMENT (Articles 32-36)
  // ============================================================================
  {
    id: 'nis2-32-1',
    framework: 'nis2',
    article_number: 'Art.32(1)',
    title: 'Supervisory Measures for Essential Entities',
    description: 'Essential entities are subject to comprehensive supervisory regime including on-site inspections, off-site supervision, and regular audits.',
    category: 'governance',
    priority: 'high',
    evidence_types: ['audit_report', 'procedure'],
    applicability: ['essential_entity'],
    sort_order: 60,
    implementation_guidance: 'Prepare for regulatory audits. Maintain documentation and evidence for supervisory reviews.',
    regulatory_reference: 'NIS2 Directive Article 32(1)',
  },
  {
    id: 'nis2-33-1',
    framework: 'nis2',
    article_number: 'Art.33(1)',
    title: 'Supervisory Measures for Important Entities',
    description: 'Important entities are subject to ex-post supervisory regime based on evidence suggesting non-compliance.',
    category: 'governance',
    priority: 'medium',
    evidence_types: ['audit_report', 'procedure'],
    applicability: ['important_entity'],
    sort_order: 61,
    implementation_guidance: 'Maintain compliance evidence. Be prepared to demonstrate compliance upon request.',
    regulatory_reference: 'NIS2 Directive Article 33(1)',
  },
  {
    id: 'nis2-34-1',
    framework: 'nis2',
    article_number: 'Art.34(1)',
    title: 'Administrative Fines Compliance',
    description: 'Understanding of administrative fine framework: up to EUR 10 million or 2% of global turnover for essential entities.',
    category: 'governance',
    priority: 'high',
    evidence_types: ['policy', 'procedure'],
    applicability: ['essential_entity', 'important_entity'],
    sort_order: 62,
    implementation_guidance: 'Ensure board awareness of penalty framework. Implement adequate compliance program.',
    regulatory_reference: 'NIS2 Directive Article 34(1)',
  },
];

export const NIS2_REQUIREMENT_COUNT = NIS2_REQUIREMENTS.length;

export function getNIS2RequirementsByCategory(category: string): FrameworkRequirement[] {
  return NIS2_REQUIREMENTS.filter(r => r.category === category);
}

export function getNIS2RequirementById(id: string): FrameworkRequirement | undefined {
  return NIS2_REQUIREMENTS.find(r => r.id === id);
}

export function getNIS2CriticalRequirements(): FrameworkRequirement[] {
  return NIS2_REQUIREMENTS.filter(r => r.priority === 'critical');
}
