/**
 * Types Module
 * Centralized type exports for the application
 */

// Common types used across all modules
export type {
  ActionResult,
  PaginationOptions,
  PaginatedResult,
  SortOptions,
  BaseFilters,
  BaseEntity,
  SoftDeletableEntity,
  Status,
  StatusInfo,
  ValidationError,
  ValidationResult,
  ApiResponse,
  ApiListResponse,
  DeepPartial,
  KeysOfType,
  RequireKeys,
  OmitNever,
  ISODateString,
  DateRange,
} from './common';

export {
  successResult,
  errorResult,
  createPaginatedResult,
} from './common';

// Database types (auto-generated by Supabase)
export type { Database } from './database.types';
